name: Lab - Schedule Next Run

on:
  schedule:
    - cron: "11 14 * * *"  # Next run at 14:10 UTC (~20:40 MMT)

jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show run time
        run: |
          echo "Scheduled workflow running (UTC & MMT)"
          echo "UTC time:"
          date -u
          echo "Myanmar Time (UTC +6:30):"
          date -u -d '+6 hours 30 minutes'

